[package]
name = "liando"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-channel = "*"
async-global-executor = "*"
rfd = "*"
serde = "*"
slint = "*"
surf = { version = "*", default-features = false, features = ["hyper-client"] }
time = { version = "*", features = ["local-offset"] }
xlsx_group_write = "*"

[build-dependencies]
slint-build = "*"
