// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

import {Button, HorizontalBox, LineEdit, StandardButton, TextEdit, VerticalBox} from "std-widgets.slint";
import {Page} from "common.slint";

export component HomePage inherits Page {
    header: "生成";
    //时间
    in-out property<string> start_date <=> start_date_edit.text;
    in-out property<string> end_date <=> end_date_edit.text;

    //按钮统一控制
    in-out property <bool> button_enabled: true;

    //文件选择
    // in-out property<string> statistics_file <=> statistics_file_edit.text;
    // callback statistics_select_clicked;
    // in-out property<string> record_file <=> record_file_edit.text;
    // callback record_select_clicked;

    //生成按钮
    callback execute_clicked;

    VerticalLayout {
        padding-top: 46px /* header line height in design */
                     + /* extra top-padding in design */ 27px;
        spacing: 24px;

        VerticalBox {
            HorizontalBox {
                width: 100%;
                vertical-stretch: 0;
                Text {
                    text: "开始日期:";
                    vertical-alignment: center;
                }
                start_date_edit := LineEdit {
                    placeholder-text: "请输入开始日期";
                }
                Text {
                    text: "结束日期:";
                    vertical-alignment: center;
                }
                end_date_edit := LineEdit {
                    placeholder-text: "请输入结束日期";
                }
            }

            HorizontalBox {vertical-stretch: 1;}

            HorizontalBox {
                horizontal-stretch: 1;
                Button {
                    vertical-stretch: 1;
                    text: "见证奇迹的时刻\n\nDUANG ！";
                    enabled: root.button_enabled;
                    clicked => {
                        root.button_enabled = false;
                        root.execute_clicked();
                    }
                }
            }
            
            HorizontalBox {vertical-stretch: 1;}
        }
    }
}
