// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

import {Button, HorizontalBox, LineEdit, StandardButton, TextEdit, VerticalBox} from "std-widgets.slint";
import {Page, Logic} from "common.slint";

export component HomePage inherits Page {
    header: "生成";

    VerticalLayout {
        padding-top: 46px /* header line height in design */
                     + /* extra top-padding in design */ 27px;
        spacing: 24px;

        VerticalBox {
            HorizontalBox {
                width: 100%;
                vertical-stretch: 0;
                Text {
                    text: "开始日期:";
                    vertical-alignment: center;
                }
                LineEdit {
                    placeholder-text: "请输入开始日期";
                    text <=> Logic.start_date;
                }
                Text {
                    text: "结束日期:";
                    vertical-alignment: center;
                }
                LineEdit {
                    placeholder-text: "请输入结束日期";
                    text <=> Logic.end-date;
                }
            }

            HorizontalBox {vertical-stretch: 1;}

            HorizontalBox {
                horizontal-stretch: 1;
                Button {
                    vertical-stretch: 1;
                    text: "见证奇迹的时刻\n\nDUANG ！";
                    enabled: Logic.button_enabled;
                    clicked => {
                        Logic.button_enabled = false;
                        Logic.home-execute-clicked();
                    }
                }
            }
            
            HorizontalBox {vertical-stretch: 1;}
        }
    }
}
