// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

import { DemoPalette, InOutProps, Label, Page } from "common.slint";
import { Button, LineEdit } from "std-widgets.slint";

export component SettingsPage inherits Page {
    header: "设置";
    //按钮统一控制
    in-out property <InOutProps> in-out-props;

    callback template-import-clicked;

    GridLayout {
        padding-top: 46px /* header line height in design */
                     + /* extra top-padding in design */ 27px;
        spacing: 24px;

        Row {
            Text {
                colspan: 6;
                text: "每日统计表";
                color: DemoPalette.secondary-foreground-color;
                font-size: DemoPalette.base-font-size * 1.125;
                font-weight: 800;
            }
        }
        Row {
            Label { text: "工号"; }
            LineEdit {
                placeholder-text: "第几列";
                text: in-out-props.statistics-employee-id;
            }

            Label { text: "考勤日期"; }
            LineEdit {
                placeholder-text: "第几列";
                text: in-out-props.statistics-date;
            }

            Label { text: "上班打卡结果"; }
            LineEdit {
                placeholder-text: "第几列";
                text: in-out-props.statistics-enter-result;
            }
        }
        Row{
            Label { text: "下班打卡结果"; }
            LineEdit {
                placeholder-text: "第几列";
                text: in-out-props.statistics-leave-result;
            }

            Label { text: "工作时长(分钟)"; }
            LineEdit {
                placeholder-text: "第几列";
                text: in-out-props.statistics-work-minutes;
            }
        }
        Row {
            Button {
                colspan: 6;
                text: "导入每日统计表";
                enabled: root.in-out-props.button_enabled;
                clicked => {
                    root.in-out-props.button_enabled = false;
                    root.template-import-clicked();
                }
            }
        }

        Row {
            Text {
                colspan: 6;
                text: "原始记录表";
                color: DemoPalette.secondary-foreground-color;
                font-size: DemoPalette.base-font-size * 1.125;
                font-weight: 800;
            }
        }
        Row {
            Label { text: "工号"; }
            LineEdit {
                placeholder-text: "第几列";
                text: in-out-props.record-employee-id;
            }

            Label { text: "考勤日期"; }
            LineEdit {
                placeholder-text: "第几列";
                text: in-out-props.record-date;
            }

            Label { text: "异常打卡原因"; }
            LineEdit {
                placeholder-text: "第几列";
                text: in-out-props.record-abnormal-reason;
            }
        }
        Row {
            Button {
                colspan: 6;
                text: "导入原始记录表";
                enabled: root.in-out-props.button_enabled;
                clicked => {
                    root.in-out-props.button_enabled = false;
                    root.template-import-clicked();
                }
            }
        }

        Row {
            Text {
                colspan: 6;
                text: "模板";
                color: DemoPalette.secondary-foreground-color;
                font-size: DemoPalette.base-font-size * 1.125;
                font-weight: 800;
            }
        }
        Row {
            Button {
                colspan: 6;
                text: "选择导出模板";
                enabled: root.in-out-props.button_enabled;
                clicked => {
                    root.in-out-props.button_enabled = false;
                    root.template-import-clicked();
                }
            }
        }

        Row{
            Rectangle {
                horizontal-stretch: 1;
                vertical-stretch: 1;
            }
        }
    }

}
