// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

import { Logic, Label, Page } from "common.slint";
import { Button, GridBox, HorizontalBox, LineEdit, TabWidget, VerticalBox} from "std-widgets.slint";

export component SettingsPage inherits Page {
    header: "设置";

    VerticalBox {
        padding-top: 46px /* header line height in design */
                   + 27px /* extra top-padding in design */ ;
        TabWidget { 
            Tab{
                title: "每日统计表";
                VerticalBox {
                    alignment: start;
                    HorizontalBox {
                        GridBox {
                            spacing: 24px;
                            Row {
                                HorizontalBox {
                                    Label { text: "工号："; width: 130px;}
                                    LineEdit {
                                        placeholder-text: "第几列";
                                        text <=> Logic.statistics-employee-id-col;
                                    }
                                    Rectangle {horizontal-stretch: 1;}
                                }
                                HorizontalBox {
                                    Label { text: "考勤日期："; width: 130px; }
                                    LineEdit {
                                        vertical-stretch: 0;
                                        placeholder-text: "第几列";
                                        text <=> Logic.statistics-date-col;
                                    }
                                    Rectangle {horizontal-stretch: 1;}
                                }
                            }
                            Row{
                                HorizontalBox {
                                    Label { text: "上班打卡结果："; width: 130px; }
                                    LineEdit {
                                        placeholder-text: "第几列";
                                        text <=> Logic.statistics-enter-result-col;
                                    }
                                    Rectangle {horizontal-stretch: 1;}
                                }
                                HorizontalBox {
                                    Label { text: "下班打卡结果："; width: 130px; }
                                    LineEdit {
                                        placeholder-text: "第几列";
                                        text <=> Logic.statistics-leave-result-col;
                                    }
                                    Rectangle {horizontal-stretch: 1;}
                                }
                            }
                            Row{
                                HorizontalBox {
                                    Label { text: "工作时长(分钟)："; width: 130px; }
                                    LineEdit {
                                        placeholder-text: "第几列";
                                        text <=> Logic.statistics-work-minutes-col;
                                    }
                                    Rectangle {horizontal-stretch: 1;}
                                }
                                HorizontalBox {
                                    Label { text: "数据起始行号："; width: 130px;  }
                                    LineEdit {
                                        placeholder-text: "第几行";
                                        text <=> Logic.statistics-start-row;
                                    }
                                    Rectangle {horizontal-stretch: 1;}
                                }
                            }
                        }
                    }
                    HorizontalBox {
                        alignment: center;
                        Button {
                            text: "📂导入每日统计表";
                            enabled: Logic.button_enabled;
                            clicked => {
                                Logic.button_enabled = false;
                                Logic.statistics-import-clicked();
                            }
                        }
                    }
                }
            }

            Tab{
                title: "原始记录表";
                VerticalBox {
                    alignment: start;
                    HorizontalBox {
                        GridBox {
                            spacing: 24px;
                            
                            Row {
                                HorizontalBox {
                                    Label { text: "工号："; width: 130px;  }
                                    LineEdit {
                                        placeholder-text: "第几列";
                                        text <=> Logic.record-employee-id-col;
                                    }
                                    Rectangle {horizontal-stretch: 1;}
                                }
                                HorizontalBox {
                                    Label { text: "考勤日期："; width: 130px;  }
                                    LineEdit {
                                        placeholder-text: "第几列";
                                        text <=> Logic.record-date-col;
                                    }
                                    Rectangle {horizontal-stretch: 1;}
                                }
                            }
                            Row {
                                HorizontalBox {
                                    Label { text: "异常打卡原因："; width: 130px;  }
                                    LineEdit {
                                        placeholder-text: "第几列";
                                        text <=> Logic.record-abnormal-reason-col;
                                    }
                                    Rectangle {horizontal-stretch: 1;}
                                }
                                HorizontalBox {
                                    Label { text: "数据起始行号："; width: 130px;  }
                                    LineEdit {
                                        placeholder-text: "第几行";
                                        text <=> Logic.record-start-row;
                                    }
                                    Rectangle {horizontal-stretch: 1;}
                                }
                            }
                        }
                    }
                    HorizontalBox {
                        alignment: center;
                        Button {
                            text: "📂导入原始记录表";
                            enabled: Logic.button_enabled;
                            clicked => {
                                Logic.button_enabled = false;
                                Logic.record-import-clicked();
                            }
                        }
                    }
                }
            }

            Tab{
                title: "模板";
                VerticalBox {
                    HorizontalBox{
                        col1 := Label {
                            text: "Sheet序号"; 
                            horizontal-alignment: center;
                            horizontal-stretch: 0.6;
                        }
                        col2 := Label {
                            text: "工号对应列（字母）";
                            horizontal-alignment: center;
                            horizontal-stretch: 1;
                        }
                        col3 := Label {
                            text: "数据起始列（字母）";
                            horizontal-alignment: center;
                            horizontal-stretch: 1;
                        }
                        col4 := Label {
                            text: "表头所在行（数字）";
                            horizontal-alignment: center;
                            horizontal-stretch: 1;
                        }
                        col5 := Label {
                            text: "操作";
                            horizontal-alignment: center;
                            horizontal-stretch: 0.5;
                        }
                    }
                    for cfg[index] in Logic.template-configs: HorizontalBox {
                        Label {
                            width: col1.width;
                            horizontal-alignment: center;
                            text: index;
                        }
                        HorizontalBox {
                            width: col2.width;
                            alignment: center;
                            LineEdit {
                                placeholder-text: "第几列";
                                text: cfg.template-employee-id-col;
                                edited => {
                                    Logic.template-configs[index].template-employee-id-col = self.text;
                                }
                            }
                        }
                        HorizontalBox {
                            width: col3.width;
                            alignment: center;
                            LineEdit {
                                placeholder-text: "第几列";
                                text: cfg.template-start-col;
                                edited => {
                                    Logic.template-configs[index].template-start-col = self.text;
                                }
                            }
                        }
                        HorizontalBox {
                            width: col4.width;
                            alignment: center;
                            LineEdit {
                                placeholder-text: "第几行";
                                text: cfg.template-title-row;
                                edited => {
                                    Logic.template-configs[index].template-title-row = self.text;
                                }
                            }
                        }
                        HorizontalBox {
                            width: col5.width;  
                            alignment: center;
                            Button {
                                text: "-";
                                enabled: Logic.button_enabled;
                                clicked => {
                                    Logic.button_enabled = false;
                                    Logic.template-remove-clicked(index);
                                }
                            }
                        }
                        
                    }
                    HorizontalBox {
                        HorizontalBox {
                            alignment: center;
                            width: col1.width;
                            Button {
                                text: "+";
                                enabled: Logic.button_enabled;
                                clicked => {
                                    Logic.button_enabled = false;
                                    Logic.template-push-clicked();
                                }
                            }
                        }
                    }
                    Rectangle {vertical-stretch: 1;}
                }
            }
        }
    }

}
